[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]
fs_permissions = [{ access = "read", path = "./testdata"}]

[dependencies]
"@openzeppelin-contracts" = "5.0.1"
forge-std = "1.9.4"
risc0-ethereum = { version = "2.0.0", url = "https://github.com/vlayer-xyz/risc0-ethereum/releases/download/v2.0.0-soldeer/contracts.zip" }
vlayer = "0.2.0-nightly-20250418-5577f23cc71d9b4095c76118c12c0eaf80307e2c"

[soldeer]
# whether soldeer manages remappings
remappings_generate = false
# whether soldeer re-generates all remappings when installing, updating or uninstalling deps
remappings_regenerate = false

